# Generated by Django 3.2.8 on 2021-11-01 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True, verbose_name='ユーザーネーム'),
        ),
    ]
