# Generated by Django 3.2.9 on 2021-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
