# Generated by Django 3.2.9 on 2022-01-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211216_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='room_title',
        ),
    ]
